#+title: Programmering B 2022 - 2024
#+subtitle: Vibenshus Gymnasium
#+author: Jacob Debel
#+date: 2022-2024
#+options: toc:t num:nil tags:t timestamp:nil ^:{}
# #+setupfile: https://fniessen.github.io/org-html-themes/org/theme-bigblow.setup
# #+setupfile: ./org-html-themes/org/theme-bigblow-local.setup
#+setupfile: ./theme-bigblow-local.setup

* Lektionsbeskrivelser
** [2022-08-29 man]                                      :arcade:funktioner:
I dag skal I til at anvende biblioteket =arcade=. Vi skal bruge det til at tegne billeder vha geometriske figurer.

- Hvis I vil forberede jer inden, så læs her: [[https://learn.arcade.academy/en/latest/chapters/05_drawing/drawing.html]]

- Jeg vil gennemgå følgende præsentation, som I kan følge med i på github: [[https://github.com/Vibenshus-Gymnasium-Programmering/Arcade_praesentationer/blob/main/02_Tegn_med_arcade/02_Tegn_med_arcade.org]]

- I skal arbejde med følgende opgave på github (classroom): [[https://classroom.github.com/a/-LD3l093]]

** Uge 34
*** [2022-08-25 tor]                                                :print:
Så går vi for alvor i gang med selve programmeringen. I dag skal vi se på de allerførste simple programstumper i =python=.

- Hvis I vil forberede jer hjemmefra, så skal I læse indholdet/se videoerne på dette link: [[https://learn.arcade.academy/en/latest/chapters/04_print_statement/print_statement.html]]

- Jeg vil gennemgå følgende "præsentation" i undervisningstiden (Det er et destillat af lektien): [[https://github.com/Vibenshus-Gymnasium-Programmering/Arcade_praesentationer/blob/main/01_printfunktionen/01_printfunktionen.org]]

- I kan finde alle præsentationer til vores forløb med =arcade=​-biblioteket her: [[https://github.com/Vibenshus-Gymnasium-Programmering/Arcade_praesentationer]]

- Endelig kommer I til at skulle arbejde med og aflevere følgende opgave på git classroom: [[https://classroom.github.com/a/_g8EyUgY]]

*** [2022-08-22 man]                                                  :git:
I dag skal der ryddes op i jeres logbøger. Måden, I skal gøre det på, er som følger:
- Opret en ny gren (branch). Den kan f.eks. hedder oprydning.
  - Ryd op i de filer, I gerne vil beholde, mens I sletter dem, som I ikke har brug for længere.
  - Det kunne f.eks. være én logbogsfil og en fil med en oversigt over, hvordan man skriver markdown- eller org mode-filer.
  - Indholdet i jeres logbog skal indeholde et afsnit over de mest anvendelige gitkommandoer og en beskrivelse af, hvordan git skal bruges.
  - Der skal også indsættes links til hjemmesider, hvor I kan læse mere om brugen af git.
- Husk at committe en eller flere gange i jeres nye gren.
- Når I er tilfredse med jeres oprydningsgren, skal I merge eller rebase indholdet til jeres main-gren.
** Uge 33
:PROPERTIES:
:VISIBILITY: folded
:END:
*** [2022-08-18 tor]                                                  :git:
Jeg kan se, at stort set alle har fået committet en ændring i deres logbog, og pushet den til github. Godt arbejde!

I dag skal vi se nærmere på, hvad git ellers kan. Til formålet anvender vi [[https://learngitbranching.js.org/]]

Når I rigtig skal bruge git til jeres udvikling af programmer. Foreslår jeg, at I anvender [[https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow][Git Feature Branch workflow]], når I arbejder alene, og [[https://docs.github.com/en/get-started/quickstart/github-flow][github flow]] når I skal til at arbejde sammen i grupper. Begge workflows går ud på at skabe nye grene (branches), og så udvikle nye features i dem. Når en feature er færdig, checker man main-grenen ud og merger med featurebranchen. Alternativt kan man, mens man står i sin featurebranch *rebase* med main, når featuren er færdig. *Dette øver vi os på med logbogen.*

I logbogen skal I som minimum skrive de kommandoer ned, som skal bruges, når man arbejder med git feature branch workflow. Altså beskriv arbejdsgangen.

*** [2022-08-15 man]                                                  :git:
Sidste gang gik der meget tid med download og opsætning af programmer.

*Dagens program er:*
- Alle skal have downloadet deres *logbog* fra deres tilhørende =git=-repo.
- Alle skal have læst README-filen og de tilhørende logbogsfiler (.md og .org)
- Alle skal have skrevet nogle noter i deres logbog, hvor der anvendes markdown- eller org mode-notation.
- Noterne skal som minimum beskrive, hvilke kommandoer der skal køres for at =committe=, og =pushe= ændringer.
- Alle skal glemme deres logbog ved at =committe= ændringerne.
- Alle skal have =pushet= deres logbøger til deres =git=-repos.

  
** Uge 32
:PROPERTIES:
:VISIBILITY: folded
:END:
*** [2022-08-11 tor]                                                :intro:

*Dagens lektie*

Alle skal gerne have installeret =git=, =python= og en editor/et IDE (vælg pycharm, hvis I er i tvivl. [[https://vibenshus-gymnasium-programmering.github.io/Introduktion/][Se præsentationen fra sidste gang]] for en vejledning til installation af programmerne.)

*Dagens program*

Vi skal i dag arbejde med brugen af =git= og vi tager udgangspunkt i præsentationen om netop =git= [[https://vibenshus-gymnasium-programmering.github.io/Git_praesentation/][her]]. I kan også finde linket til præsentationen under fanen Præsentationer her på siden.


*** [2022-08-08 man]                                                :intro:
I dag står den på introduktion til faget programmering B. I kan finde den tilhørende præsentationer under fanen Præsentationer her på siden.

Efter selve introduktionen til faget går vi så småt i gang med at installere det programmel (det danske ord for software), som vi skal bruge.

[[https://vibenshus-gymnasium-programmering.github.io/Introduktion/]]

*Post Scriptum*
Så er vi ligesom i gang. Det var dejligt at lære jer at kende. Det skal nok blive et rigtig godt år!
* Præsentationer

** Arcade

Her er et link til alle præsentationerne anvendt i forløbet omkring =arcade=​-bibliotektet.

[[https://github.com/Vibenshus-Gymnasium-Programmering/Arcade_praesentationer]]

Hver præsentation er blot en =org mode=-fil, som vil blive fremvist i emacs. Fidusen ved dette er, at kodestumperne kan eksekveres direkte fra emacs, og der kan ændres i koden direkte, uden at skulle åbne et andet program.

** Git

Her er præsentationen til opsætning af og opgaverne om ~git~.

[[https://vibenshus-gymnasium-programmering.github.io/Git_praesentation/]]

** Introduktion til faget

Her er præsentationen til faget. Åbn linket i en anden tab/et andet vindue.

[[https://vibenshus-gymnasium-programmering.github.io/Introduktion/]]

* Opgaver
** Arcade
*** Opgave 02 Tegn et billede
Her er linket til jeres anden opgave. I denne opgave skal I anvende biblioteket =arcade= til at tegne billeder vha geometriske figurer. Det er en øvelse i at kalde funktioner i python.

[[https://classroom.github.com/a/-LD3l093]]

*** Opgave 01 Printfunktionen
Her er linket til jeres første opgave, som har noget med pythonkode at gøre.

[[https://classroom.github.com/a/_g8EyUgY]]

Sørg for at klone jeres tildelte repo ned på jeres lokale maskine.
** Logbog
Opret jeres logbog ved at følge linket her: [[https://classroom.github.com/a/slPR9059]]

Sørg for at føre logbog hver uge. Der bliver holdt øje med jer. :)

* UVB
** Git
** Grundlæggende programmering med ~python arcade~
** Udvikling af GUIs med ~pyside6~
** Kryptografi
** Robotstyring - Lego Mindstorms
** Machine Learning
* Om
Dette er en simpel hjemmeside knyttet til programmering B på Vibenshus Gymnasium for skoleårene 2022-2024.

Faktisk er der blot tale om en simpel org-mode-fil, som er eksporteret til html og css vha. [[https://github.com/fniessen/org-html-themes]].
